// <auto-generated />
using System;
using LorafyAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LorafyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LorafyAPI.Entities.EndDevice", b =>
                {
                    b.Property<string>("EUI")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EUI");

                    b.ToTable("EndDevices");
                });

            modelBuilder.Entity("LorafyAPI.Entities.Gateway", b =>
                {
                    b.Property<string>("EUI")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RSSI")
                        .HasColumnType("int");

                    b.Property<float>("SNR")
                        .HasColumnType("float");

                    b.HasKey("EUI");

                    b.ToTable("Gateways");
                });

            modelBuilder.Entity("LorafyAPI.Entities.UplinkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndDeviceEUI")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GatewayEUI")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EndDeviceEUI");

                    b.HasIndex("GatewayEUI");

                    b.ToTable("UplinkMessages");
                });

            modelBuilder.Entity("LorafyAPI.Entities.Gateway", b =>
                {
                    b.OwnsOne("LorafyAPI.Entities.GatewayLocation", "Location", b1 =>
                        {
                            b1.Property<string>("GatewayEUI")
                                .HasColumnType("varchar(255)");

                            b1.Property<float?>("Altitude")
                                .HasColumnType("float");

                            b1.Property<float?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<float?>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("GatewayEUI");

                            b1.ToTable("Gateways");

                            b1.WithOwner()
                                .HasForeignKey("GatewayEUI");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("LorafyAPI.Entities.UplinkMessage", b =>
                {
                    b.HasOne("LorafyAPI.Entities.EndDevice", "EndDevice")
                        .WithMany("UplinkMessages")
                        .HasForeignKey("EndDeviceEUI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LorafyAPI.Entities.Gateway", "Gateway")
                        .WithMany("UplinkMessages")
                        .HasForeignKey("GatewayEUI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LorafyAPI.Entities.UplinkMessageDataRate", "DataRate", b1 =>
                        {
                            b1.Property<int>("UplinkMessageId")
                                .HasColumnType("int");

                            b1.Property<int>("Bandwidth")
                                .HasColumnType("int");

                            b1.Property<string>("CodingRate")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("SpreadingFactor")
                                .HasColumnType("int");

                            b1.HasKey("UplinkMessageId");

                            b1.ToTable("UplinkMessages");

                            b1.WithOwner()
                                .HasForeignKey("UplinkMessageId");
                        });

                    b.OwnsOne("LorafyAPI.Entities.UplinkMessagePayload", "Payload", b1 =>
                        {
                            b1.Property<int>("UplinkMessageId")
                                .HasColumnType("int");

                            b1.Property<float?>("Battery")
                                .HasColumnType("float");

                            b1.Property<float?>("BatteryVoltage")
                                .HasColumnType("float");

                            b1.Property<float?>("Humidity")
                                .HasColumnType("float");

                            b1.Property<float?>("Light")
                                .HasColumnType("float");

                            b1.Property<float?>("Pressure")
                                .HasColumnType("float");

                            b1.Property<float?>("TemperatureInside")
                                .HasColumnType("float");

                            b1.Property<float?>("TemperatureOutside")
                                .HasColumnType("float");

                            b1.HasKey("UplinkMessageId");

                            b1.ToTable("UplinkMessages");

                            b1.WithOwner()
                                .HasForeignKey("UplinkMessageId");
                        });

                    b.Navigation("DataRate")
                        .IsRequired();

                    b.Navigation("EndDevice");

                    b.Navigation("Gateway");

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("LorafyAPI.Entities.EndDevice", b =>
                {
                    b.Navigation("UplinkMessages");
                });

            modelBuilder.Entity("LorafyAPI.Entities.Gateway", b =>
                {
                    b.Navigation("UplinkMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
